// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogHomeDocumentDataSlicesSlice = BannerSlice | BlogPostListSlice | TestimonialsMarqueeSlice

/**
 * Content for Blog Home documents
 */
interface BlogHomeDocumentData {
	/**
	 * Slice Zone field in *Blog Home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<BlogHomeDocumentDataSlicesSlice>;/**
	 * Keyword field in *Blog Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_home.keyword
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	keyword: prismic.KeyTextField;
	
	/**
	 * Meta Title field in *Blog Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_home.meta_title
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta Description field in *Blog Home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_home.meta_description
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG Image field in *Blog Home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_home.og_image
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Blog Home document from Prismic
 *
 * - **API ID**: `blog_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogHomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<BlogHomeDocumentData>, "blog_home", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSliceSlice | ImageFeaturedStandardSlice | BookTableSlice | LoveContentSlice | TestimonialsGallerySlice | TakeAwaySlice | TestimonialsMarqueeSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;/**
	 * Keyword field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.keyword
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	keyword: prismic.KeyTextField;
	
	/**
	 * NO INDEX field in *Homepage*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: homepage.no_index
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	no_index: prismic.BooleanField;
	
	/**
	 * Meta title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_title
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	og_title: prismic.KeyTextField;
	
	/**
	 * OG description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_description
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	og_description: prismic.KeyTextField;
	
	/**
	 * OG image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_image
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *Menu → Menu Links*
 */
export interface MenuDocumentDataMenuLinksItem {
	/**
	 * Link Label field in *Menu → Menu Links*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Link Label...
	 * - **API ID Path**: menu.menuLinks[].label
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	label: prismic.RichTextField;
	
	/**
	 * Link field in *Menu → Menu Links*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select a Link...
	 * - **API ID Path**: menu.menuLinks[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type MenuDocumentDataSlicesSlice = TakeAwaySlice | ValuesListSlice | BookTableSlice

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
	/**
	 * `title` field in *Menu*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Menu title...
	 * - **API ID Path**: menu.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Menu Links field in *Menu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.menuLinks[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	menuLinks: prismic.GroupField<Simplify<MenuDocumentDataMenuLinksItem>>;
	
	/**
	 * Slice Zone field in *Menu*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<MenuDocumentDataSlicesSlice>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice = BannerSlice | AddressesBoxSlice | AllergyBoxSlice | DrinksMenuSlice | BookTableSlice | GalleryListSlice | ImageGallerySlice | ImageFeaturedStandardSlice | HeroSliceSlice | LoveContentSlice | MainMenuSlice | MapBoxSlice | TestimonialsGallerySlice | TeamSliceSlice | StoryFeaturedSlice | ValuesListSlice | VeganMenuSlice | TakeAwaySlice | TestimonialsMarqueeSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;/**
	 * Keyword field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.keyword
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	keyword: prismic.KeyTextField;
	
	/**
	 * Meta title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.og_title
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	og_title: prismic.KeyTextField;
	
	/**
	 * OG description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.og_description
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	og_description: prismic.KeyTextField;
	
	/**
	 * OG image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.og_image
	 * - **Tab**: SEO TAB
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;/**
	 * Active redirect field in *Page*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: page.active_redirect
	 * - **Tab**: Redirect
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	active_redirect: prismic.BooleanField;
	
	/**
	 * Redirect link field in *Page*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.redirect_link
	 * - **Tab**: Redirect
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	redirect_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for reservations documents
 */
interface ReservationsDocumentData {
	/**
	 * username field in *reservations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reservations.username
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	username: prismic.KeyTextField;
	
	/**
	 * password field in *reservations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: reservations.password
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	password: prismic.KeyTextField;
}

/**
 * reservations document from Prismic
 *
 * - **API ID**: `reservations`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReservationsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<ReservationsDocumentData>, "reservations", Lang>;

type StandardpageDocumentDataSlicesSlice = HeroSliceSlice | ImageGallerySlice | BannerSlice

/**
 * Content for OLDCUSTOMTYPE documents
 */
interface StandardpageDocumentData {
	/**
	 * Title field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * not used field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.not_used
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	not_used: prismic.RichTextField;
	
	/**
	 * Slice Zone field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<StandardpageDocumentDataSlicesSlice>;/**
	 * NO INDEX field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: standardpage.no_index
	 * - **Tab**: SEO tab
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	no_index: prismic.BooleanField;
	
	/**
	 * Canonical URL field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.canonical_url
	 * - **Tab**: SEO tab
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	canonical_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Meta title field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.meta_title
	 * - **Tab**: SEO tab
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
	
	/**
	 * Meta description field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.meta_description
	 * - **Tab**: SEO tab
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;
	
	/**
	 * OG title field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.og_title
	 * - **Tab**: SEO tab
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	og_title: prismic.KeyTextField;
	
	/**
	 * OG description field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.og_description
	 * - **Tab**: SEO tab
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	og_description: prismic.KeyTextField;
	
	/**
	 * OG image field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.og_image
	 * - **Tab**: SEO tab
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	og_image: prismic.ImageField<never>;/**
	 * Active redirect field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: standardpage.active_redirect
	 * - **Tab**: Redirect
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	active_redirect: prismic.BooleanField;
	
	/**
	 * Redirect link field in *OLDCUSTOMTYPE*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: standardpage.redirect_link
	 * - **Tab**: Redirect
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	redirect_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * OLDCUSTOMTYPE document from Prismic
 *
 * - **API ID**: `standardpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StandardpageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<StandardpageDocumentData>, "standardpage", Lang>;

export type AllDocumentTypes = BlogHomeDocument | HomepageDocument | MenuDocument | PageDocument | ReservationsDocument | StandardpageDocument;

/**
 * Primary content in *AddressesBox → Default → Primary*
 */
export interface AddressesBoxSliceDefaultPrimary {
	/**
	 * Illustration field in *AddressesBox → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: addresses_box.default.primary.illustration
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	illustration: prismic.ImageField<never>;
}

/**
 * Primary content in *AddressesBox → Items*
 */
export interface AddressesBoxSliceDefaultItem {
	/**
	 * Title field in *AddressesBox → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: addresses_box.items[].title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *AddressesBox → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: addresses_box.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for AddressesBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: AddressesBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressesBoxSliceDefault = prismic.SharedSliceVariation<"default", Simplify<AddressesBoxSliceDefaultPrimary>, Simplify<AddressesBoxSliceDefaultItem>>;

/**
 * Slice variation for *AddressesBox*
 */
type AddressesBoxSliceVariation = AddressesBoxSliceDefault

/**
 * AddressesBox Shared Slice
 *
 * - **API ID**: `addresses_box`
 * - **Description**: AddressesBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AddressesBoxSlice = prismic.SharedSlice<"addresses_box", AddressesBoxSliceVariation>;

/**
 * Primary content in *AllergyBox → Default → Primary*
 */
export interface AllergyBoxSliceDefaultPrimary {
	/**
	 * AllergiesTitle field in *AllergyBox → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: allergy_box.default.primary.allergiestitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	allergiestitle: prismic.TitleField;
	
	/**
	 * Emoji field in *AllergyBox → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: allergy_box.default.primary.emoji
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	emoji: prismic.KeyTextField;
	
	/**
	 * Title field in *AllergyBox → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: allergy_box.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *AllergyBox → Items*
 */
export interface AllergyBoxSliceDefaultItem {
	/**
	 * paragraph field in *AllergyBox → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: allergy_box.items[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Default variation for AllergyBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: AllergyBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllergyBoxSliceDefault = prismic.SharedSliceVariation<"default", Simplify<AllergyBoxSliceDefaultPrimary>, Simplify<AllergyBoxSliceDefaultItem>>;

/**
 * Slice variation for *AllergyBox*
 */
type AllergyBoxSliceVariation = AllergyBoxSliceDefault

/**
 * AllergyBox Shared Slice
 *
 * - **API ID**: `allergy_box`
 * - **Description**: AllergyBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AllergyBoxSlice = prismic.SharedSlice<"allergy_box", AllergyBoxSliceVariation>;

/**
 * Primary content in *BannerSlice → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
	/**
	 * Title field in *BannerSlice → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: banner.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * description field in *BannerSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * BackgroundImage field in *BannerSlice → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: banner.default.primary.backgroundimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	backgroundimage: prismic.ImageField<never>;
}

/**
 * Default variation for BannerSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BannerSliceDefaultPrimary>, never>;

/**
 * Slice variation for *BannerSlice*
 */
type BannerSliceVariation = BannerSliceDefault

/**
 * BannerSlice Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BlogPostList → Default → Primary*
 */
export interface BlogPostListSliceDefaultPrimary {
	/**
	 * Title field in *BlogPostList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Description field in *BlogPostList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post_list.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
}

/**
 * Default variation for BlogPostList Slice
 *
 * - **API ID**: `default`
 * - **Description**: BlogPostList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BlogPostListSliceDefaultPrimary>, never>;

/**
 * Slice variation for *BlogPostList*
 */
type BlogPostListSliceVariation = BlogPostListSliceDefault

/**
 * BlogPostList Shared Slice
 *
 * - **API ID**: `blog_post_list`
 * - **Description**: BlogPostList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogPostListSlice = prismic.SharedSlice<"blog_post_list", BlogPostListSliceVariation>;

/**
 * Primary content in *BookTable → Default → Primary*
 */
export interface BookTableSliceDefaultPrimary {
	/**
	 * emoji field in *BookTable → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: book_table.default.primary.emoji
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	emoji: prismic.KeyTextField;
	
	/**
	 * Title field in *BookTable → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: book_table.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * BookTable field in *BookTable → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: book_table.default.primary.booktable
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	booktable: prismic.TitleField;
	
	/**
	 * CTA Internal Link field in *BookTable → Default → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: book_table.default.primary.cta_internal_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_internal_link: prismic.ContentRelationshipField;
	
	/**
	 * CTA Text Internal Link field in *BookTable → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: book_table.default.primary.cta_text_internal_link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text_internal_link: prismic.KeyTextField;
	
	/**
	 * backgroundImage field in *BookTable → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: book_table.default.primary.backgroundimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	backgroundimage: prismic.ImageField<never>;
}

/**
 * Primary content in *BookTable → Items*
 */
export interface BookTableSliceDefaultItem {
	/**
	 * paragraph field in *BookTable → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: book_table.items[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Default variation for BookTable Slice
 *
 * - **API ID**: `default`
 * - **Description**: BookTable
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookTableSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BookTableSliceDefaultPrimary>, Simplify<BookTableSliceDefaultItem>>;

/**
 * Slice variation for *BookTable*
 */
type BookTableSliceVariation = BookTableSliceDefault

/**
 * BookTable Shared Slice
 *
 * - **API ID**: `book_table`
 * - **Description**: BookTable
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BookTableSlice = prismic.SharedSlice<"book_table", BookTableSliceVariation>;

/**
 * Primary content in *DrinksMenu → Default → Primary*
 */
export interface DrinksMenuSliceDefaultPrimary {
	/**
	 * Title field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: drinks_menu.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Illustration field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.illustration
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	illustration: prismic.ImageField<never>;
	
	/**
	 * SimpleDouble field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.simpledouble
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	simpledouble: prismic.KeyTextField;
	
	/**
	 * TopDrinkTitle1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle1
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle1: prismic.TitleField;
	
	/**
	 * TopDrinkPrice1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice1: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription1: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext1
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext1: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle2: prismic.TitleField;
	
	/**
	 * TopDrinkPrice2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice2: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription2: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext2: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle3
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle3: prismic.TitleField;
	
	/**
	 * TopDrinkPrice3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice3: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription3: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext3
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext3: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle4
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle4: prismic.TitleField;
	
	/**
	 * TopDrinkPrice4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice4
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice4: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription4
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription4: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext4
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext4: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle5
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle5: prismic.TitleField;
	
	/**
	 * TopDrinkPrice5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice5
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice5: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription5
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription5: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext5
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext5: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle6
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle6: prismic.TitleField;
	
	/**
	 * TopDrinkPrice6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice6
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice6: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription6
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription6: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext6
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext6: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle7
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle7: prismic.TitleField;
	
	/**
	 * TopDrinkPrice7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice7
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice7: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription7
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription7: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext7
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext7: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle8
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle8: prismic.TitleField;
	
	/**
	 * TopDrinkPrice8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice8
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice8: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription8
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription8: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext8
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext8: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle9
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle9: prismic.TitleField;
	
	/**
	 * TopDrinkPrice9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice9
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice9: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription9
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription9: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext9
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext9: prismic.RichTextField;
	
	/**
	 * TopDrinkTitle10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinktitle10
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinktitle10: prismic.TitleField;
	
	/**
	 * TopDrinkPrice10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkprice10
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkprice10: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescription10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescription10
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	topdrinkdescription10: prismic.KeyTextField;
	
	/**
	 * TopDrinkDescriptionRichText10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.topdrinkdescriptionrichtext10
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	topdrinkdescriptionrichtext10: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle1
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle1: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice1: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription1: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText1 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext1
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext1: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle2: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice2: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription2: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText2 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext2: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle3
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle3: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice3: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription3: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText3 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext3
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext3: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle4
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle4: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice4
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice4: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription4
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription4: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText4 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext4
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext4: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle5
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle5: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice5
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice5: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription5
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription5: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText5 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext5
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext5: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle6
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle6: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice6
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice6: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription6
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription6: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText6 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext6
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext6: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle7
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle7: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice7
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice7: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription7
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription7: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText7 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext7
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext7: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle8
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle8: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice8
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice8: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription8
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription8: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText8 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext8
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext8: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle9
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle9: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice9
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice9: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription9
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription9: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText9 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext9
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext9: prismic.RichTextField;
	
	/**
	 * BtmDrinkTitle10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinktitle10
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinktitle10: prismic.TitleField;
	
	/**
	 * BtmDrinkPrice10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkprice10
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkprice10: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescription10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescription10
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	btmdrinkdescription10: prismic.KeyTextField;
	
	/**
	 * BtmDrinkDescriptionRichText10 field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.btmdrinkdescriptionrichtext10
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	btmdrinkdescriptionrichtext10: prismic.RichTextField;
	
	/**
	 * Instruction field in *DrinksMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.default.primary.instruction
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	instruction: prismic.KeyTextField;
}

/**
 * Primary content in *DrinksMenu → Items*
 */
export interface DrinksMenuSliceDefaultItem {
	/**
	 * DrinkTitle field in *DrinksMenu → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.items[].drinktitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	drinktitle: prismic.TitleField;
	
	/**
	 * Price field in *DrinksMenu → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.items[].price
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	price: prismic.KeyTextField;
	
	/**
	 * Description field in *DrinksMenu → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * DescriptionRichText field in *DrinksMenu → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: drinks_menu.items[].descriptionrichtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	descriptionrichtext: prismic.RichTextField;
}

/**
 * Default variation for DrinksMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: DrinksMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DrinksMenuSliceDefault = prismic.SharedSliceVariation<"default", Simplify<DrinksMenuSliceDefaultPrimary>, Simplify<DrinksMenuSliceDefaultItem>>;

/**
 * Slice variation for *DrinksMenu*
 */
type DrinksMenuSliceVariation = DrinksMenuSliceDefault

/**
 * DrinksMenu Shared Slice
 *
 * - **API ID**: `drinks_menu`
 * - **Description**: DrinksMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DrinksMenuSlice = prismic.SharedSlice<"drinks_menu", DrinksMenuSliceVariation>;

/**
 * Primary content in *GalleryList → Items*
 */
export interface GalleryListSliceDefaultItem {
	/**
	 * Image field in *GalleryList → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery_list.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for GalleryList Slice
 *
 * - **API ID**: `default`
 * - **Description**: GalleryList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryListSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<GalleryListSliceDefaultItem>>;

/**
 * Slice variation for *GalleryList*
 */
type GalleryListSliceVariation = GalleryListSliceDefault

/**
 * GalleryList Shared Slice
 *
 * - **API ID**: `gallery_list`
 * - **Description**: GalleryList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GalleryListSlice = prismic.SharedSlice<"gallery_list", GalleryListSliceVariation>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
	/**
	 * Title field in *HeroSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: hero_slice.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * Description field in *HeroSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_slice.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * image field in *HeroSlice → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_slice.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * CTA Internal Link field in *HeroSlice → Default → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_slice.default.primary.cta_internal_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_internal_link: prismic.ContentRelationshipField;
	
	/**
	 * CTA text field in *HeroSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_slice.default.primary.cta_text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text: prismic.KeyTextField;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceSliceDefaultPrimary>, never>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation = HeroSliceSliceDefault

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<"hero_slice", HeroSliceSliceVariation>;

/**
 * Primary content in *ImageFeaturedStandard → Default → Primary*
 */
export interface ImageFeaturedStandardSliceDefaultPrimary {
	/**
	 * Subtitle field in *ImageFeaturedStandard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_featured_standard.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Secondary Heading field in *ImageFeaturedStandard → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: image_featured_standard.default.primary.secondary_heading
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	secondary_heading: prismic.TitleField;
	
	/**
	 * Image field in *ImageFeaturedStandard → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_featured_standard.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * CTA Internal Link field in *ImageFeaturedStandard → Default → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_featured_standard.default.primary.cta_internal_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_internal_link: prismic.ContentRelationshipField;
	
	/**
	 * CTA Text Link field in *ImageFeaturedStandard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_featured_standard.default.primary.cta_text_link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text_link: prismic.KeyTextField;
	
	/**
	 * CTA Internal Link 2 field in *ImageFeaturedStandard → Default → Primary*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_featured_standard.default.primary.cta_internal_link_2
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_internal_link_2: prismic.ContentRelationshipField;
	
	/**
	 * CTA Text Link 2 field in *ImageFeaturedStandard → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_featured_standard.default.primary.cta_text_link_2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text_link_2: prismic.KeyTextField;
}

/**
 * Primary content in *ImageFeaturedStandard → Items*
 */
export interface ImageFeaturedStandardSliceDefaultItem {
	/**
	 * Paragraph field in *ImageFeaturedStandard → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_featured_standard.items[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Default variation for ImageFeaturedStandard Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageFeaturedStandard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageFeaturedStandardSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ImageFeaturedStandardSliceDefaultPrimary>, Simplify<ImageFeaturedStandardSliceDefaultItem>>;

/**
 * Slice variation for *ImageFeaturedStandard*
 */
type ImageFeaturedStandardSliceVariation = ImageFeaturedStandardSliceDefault

/**
 * ImageFeaturedStandard Shared Slice
 *
 * - **API ID**: `image_featured_standard`
 * - **Description**: ImageFeaturedStandard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageFeaturedStandardSlice = prismic.SharedSlice<"image_featured_standard", ImageFeaturedStandardSliceVariation>;

/**
 * Primary content in *ImageGallery → Default → Primary*
 */
export interface ImageGallerySliceDefaultPrimary {
	/**
	 * Title field in *ImageGallery → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: image_gallery.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *ImageGallery → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: A nice description of your feature
	 * - **API ID Path**: image_gallery.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Primary content in *ImageGallery → Items*
 */
export interface ImageGallerySliceDefaultItem {
	/**
	 * Image field in *ImageGallery → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: image_gallery.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<"default", Simplify<ImageGallerySliceDefaultPrimary>, Simplify<ImageGallerySliceDefaultItem>>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySlice = prismic.SharedSlice<"image_gallery", ImageGallerySliceVariation>;

/**
 * Primary content in *LoveContent → Default → Primary*
 */
export interface LoveContentSliceDefaultPrimary {
	/**
	 * TitleImpact field in *LoveContent → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: love_content.default.primary.titleimpact
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	titleimpact: prismic.RichTextField;
	
	/**
	 * Sentence field in *LoveContent → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: love_content.default.primary.sentence
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	sentence: prismic.KeyTextField;
}

/**
 * Default variation for LoveContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: LoveContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LoveContentSliceDefault = prismic.SharedSliceVariation<"default", Simplify<LoveContentSliceDefaultPrimary>, never>;

/**
 * Slice variation for *LoveContent*
 */
type LoveContentSliceVariation = LoveContentSliceDefault

/**
 * LoveContent Shared Slice
 *
 * - **API ID**: `love_content`
 * - **Description**: LoveContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LoveContentSlice = prismic.SharedSlice<"love_content", LoveContentSliceVariation>;

/**
 * Primary content in *MainMenu → Default → Primary*
 */
export interface MainMenuSliceDefaultPrimary {
	/**
	 * Title field in *MainMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: main_menu.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *MainMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Illustration field in *MainMenu → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.default.primary.illustration
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	illustration: prismic.ImageField<never>;
	
	/**
	 * HighlightedBreakfastTitle field in *MainMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.default.primary.highlightedbreakfasttitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	highlightedbreakfasttitle: prismic.TitleField;
	
	/**
	 * HighlightedBreakfastPrice field in *MainMenu → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.default.primary.highlightedbreakfastprice
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	highlightedbreakfastprice: prismic.NumberField;
	
	/**
	 * HighlightedBreakfastDescription field in *MainMenu → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.default.primary.highlightedbreakfastdescription
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	highlightedbreakfastdescription: prismic.RichTextField;
}

/**
 * Primary content in *MainMenu → Items*
 */
export interface MainMenuSliceDefaultItem {
	/**
	 * BreakfastTitle field in *MainMenu → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.items[].breakfasttitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	breakfasttitle: prismic.TitleField;
	
	/**
	 * Price field in *MainMenu → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.items[].price
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;
	
	/**
	 * Description field in *MainMenu → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: main_menu.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for MainMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: MainMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainMenuSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MainMenuSliceDefaultPrimary>, Simplify<MainMenuSliceDefaultItem>>;

/**
 * Slice variation for *MainMenu*
 */
type MainMenuSliceVariation = MainMenuSliceDefault

/**
 * MainMenu Shared Slice
 *
 * - **API ID**: `main_menu`
 * - **Description**: MainMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainMenuSlice = prismic.SharedSlice<"main_menu", MainMenuSliceVariation>;

/**
 * Primary content in *MapBox → Default → Primary*
 */
export interface MapBoxSliceDefaultPrimary {
	/**
	 * Description field in *MapBox → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: map_box.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
}

/**
 * Default variation for MapBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: MapBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapBoxSliceDefault = prismic.SharedSliceVariation<"default", Simplify<MapBoxSliceDefaultPrimary>, never>;

/**
 * Slice variation for *MapBox*
 */
type MapBoxSliceVariation = MapBoxSliceDefault

/**
 * MapBox Shared Slice
 *
 * - **API ID**: `map_box`
 * - **Description**: MapBox
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapBoxSlice = prismic.SharedSlice<"map_box", MapBoxSliceVariation>;

/**
 * Primary content in *StoryFeatured → Default → Primary*
 */
export interface StoryFeaturedSliceDefaultPrimary {
	/**
	 * Subtitle field in *StoryFeatured → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: story_featured.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Title field in *StoryFeatured → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: story_featured.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Image field in *StoryFeatured → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: story_featured.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *StoryFeatured → Items*
 */
export interface StoryFeaturedSliceDefaultItem {
	/**
	 * paragraph field in *StoryFeatured → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: story_featured.items[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Default variation for StoryFeatured Slice
 *
 * - **API ID**: `default`
 * - **Description**: StoryFeatured
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoryFeaturedSliceDefault = prismic.SharedSliceVariation<"default", Simplify<StoryFeaturedSliceDefaultPrimary>, Simplify<StoryFeaturedSliceDefaultItem>>;

/**
 * Slice variation for *StoryFeatured*
 */
type StoryFeaturedSliceVariation = StoryFeaturedSliceDefault

/**
 * StoryFeatured Shared Slice
 *
 * - **API ID**: `story_featured`
 * - **Description**: StoryFeatured
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StoryFeaturedSlice = prismic.SharedSlice<"story_featured", StoryFeaturedSliceVariation>;

/**
 * Primary content in *TakeAway → Default → Primary*
 */
export interface TakeAwaySliceDefaultPrimary {
	/**
	 * emoji field in *TakeAway → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: take_away.default.primary.emoji
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	emoji: prismic.KeyTextField;
	
	/**
	 * Title field in *TakeAway → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: take_away.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.RichTextField;
	
	/**
	 * TakeAwayTitleOverlay field in *TakeAway → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: take_away.default.primary.takeawaytitleoverlay
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	takeawaytitleoverlay: prismic.TitleField;
	
	/**
	 * CTA link field in *TakeAway → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: take_away.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * CTA Text Internal Link field in *TakeAway → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: take_away.default.primary.cta_text_internal_link
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text_internal_link: prismic.KeyTextField;
	
	/**
	 * backgroundImage field in *TakeAway → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: take_away.default.primary.backgroundimage
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	backgroundimage: prismic.ImageField<never>;
}

/**
 * Primary content in *TakeAway → Items*
 */
export interface TakeAwaySliceDefaultItem {
	/**
	 * paragraph field in *TakeAway → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: take_away.items[].paragraph
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	paragraph: prismic.RichTextField;
}

/**
 * Default variation for TakeAway Slice
 *
 * - **API ID**: `default`
 * - **Description**: TakeAway
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TakeAwaySliceDefault = prismic.SharedSliceVariation<"default", Simplify<TakeAwaySliceDefaultPrimary>, Simplify<TakeAwaySliceDefaultItem>>;

/**
 * Slice variation for *TakeAway*
 */
type TakeAwaySliceVariation = TakeAwaySliceDefault

/**
 * TakeAway Shared Slice
 *
 * - **API ID**: `take_away`
 * - **Description**: TakeAway
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TakeAwaySlice = prismic.SharedSlice<"take_away", TakeAwaySliceVariation>;

/**
 * Primary content in *TeamSlice → Default → Primary*
 */
export interface TeamSliceSliceDefaultPrimary {
	/**
	 * subtitle field in *TeamSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_slice.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Title field in *TeamSlice → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: team_slice.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
}

/**
 * Primary content in *TeamSlice → Items*
 */
export interface TeamSliceSliceDefaultItem {
	/**
	 * Photo field in *TeamSlice → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_slice.items[].photo
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	photo: prismic.ImageField<never>;
	
	/**
	 * Names field in *TeamSlice → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_slice.items[].names
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	names: prismic.TitleField;
	
	/**
	 * Position Title field in *TeamSlice → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_slice.items[].position_title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	position_title: prismic.KeyTextField;
	
	/**
	 * Description field in *TeamSlice → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: team_slice.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	description: prismic.RichTextField;
}

/**
 * Default variation for TeamSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: TeamSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TeamSliceSliceDefaultPrimary>, Simplify<TeamSliceSliceDefaultItem>>;

/**
 * Slice variation for *TeamSlice*
 */
type TeamSliceSliceVariation = TeamSliceSliceDefault

/**
 * TeamSlice Shared Slice
 *
 * - **API ID**: `team_slice`
 * - **Description**: TeamSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceSlice = prismic.SharedSlice<"team_slice", TeamSliceSliceVariation>;

/**
 * Primary content in *TestimonialsGallery → Default → Primary*
 */
export interface TestimonialsGallerySliceDefaultPrimary {
	/**
	 * subtitle field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_gallery.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Title field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: testimonials_gallery.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Image1 field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_gallery.default.primary.image1
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image1: prismic.ImageField<never>;
	
	/**
	 * Image2 field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_gallery.default.primary.image2
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image2: prismic.ImageField<never>;
	
	/**
	 * Image3 field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_gallery.default.primary.image3
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image3: prismic.ImageField<never>;
	
	/**
	 * Image4 field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_gallery.default.primary.image4
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image4: prismic.ImageField<never>;
	
	/**
	 * Image5 field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_gallery.default.primary.image5
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image5: prismic.ImageField<never>;
	
	/**
	 * Image6 field in *TestimonialsGallery → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_gallery.default.primary.image6
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image6: prismic.ImageField<never>;
}

/**
 * Default variation for TestimonialsGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: TestimonialsGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsGallerySliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialsGallerySliceDefaultPrimary>, never>;

/**
 * Slice variation for *TestimonialsGallery*
 */
type TestimonialsGallerySliceVariation = TestimonialsGallerySliceDefault

/**
 * TestimonialsGallery Shared Slice
 *
 * - **API ID**: `testimonials_gallery`
 * - **Description**: TestimonialsGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsGallerySlice = prismic.SharedSlice<"testimonials_gallery", TestimonialsGallerySliceVariation>;

/**
 * Primary content in *TestimonialsMarquee → Default → Primary*
 */
export interface TestimonialsMarqueeSliceDefaultPrimary {
	/**
	 * Title field in *TestimonialsMarquee → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials_marquee.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;
}

/**
 * Default variation for TestimonialsMarquee Slice
 *
 * - **API ID**: `default`
 * - **Description**: TestimonialsMarquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsMarqueeSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialsMarqueeSliceDefaultPrimary>, never>;

/**
 * Slice variation for *TestimonialsMarquee*
 */
type TestimonialsMarqueeSliceVariation = TestimonialsMarqueeSliceDefault

/**
 * TestimonialsMarquee Shared Slice
 *
 * - **API ID**: `testimonials_marquee`
 * - **Description**: TestimonialsMarquee
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsMarqueeSlice = prismic.SharedSlice<"testimonials_marquee", TestimonialsMarqueeSliceVariation>;

/**
 * Primary content in *ValuesList → Default → Primary*
 */
export interface ValuesListSliceDefaultPrimary {
	/**
	 * ValueIcon1 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valueicon1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	valueicon1: prismic.KeyTextField;
	
	/**
	 * ValueTitle1 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valuetitle1
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	valuetitle1: prismic.TitleField;
	
	/**
	 * ValueDescription1 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valuedescription1
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	valuedescription1: prismic.KeyTextField;
	
	/**
	 * ValueIcon2 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valueicon2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	valueicon2: prismic.KeyTextField;
	
	/**
	 * ValueTitle2 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valuetitle2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	valuetitle2: prismic.TitleField;
	
	/**
	 * ValueDescription2 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valuedescription2
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	valuedescription2: prismic.KeyTextField;
	
	/**
	 * ValueIcon3 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valueicon3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	valueicon3: prismic.KeyTextField;
	
	/**
	 * ValueTitle3 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valuetitle3
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	valuetitle3: prismic.TitleField;
	
	/**
	 * ValueDescription3 field in *ValuesList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: values_list.default.primary.valuedescription3
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	valuedescription3: prismic.KeyTextField;
}

/**
 * Default variation for ValuesList Slice
 *
 * - **API ID**: `default`
 * - **Description**: ValuesList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuesListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ValuesListSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ValuesList*
 */
type ValuesListSliceVariation = ValuesListSliceDefault

/**
 * ValuesList Shared Slice
 *
 * - **API ID**: `values_list`
 * - **Description**: ValuesList
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ValuesListSlice = prismic.SharedSlice<"values_list", ValuesListSliceVariation>;

/**
 * Primary content in *VeganMenu → Default → Primary*
 */
export interface VeganMenuSliceDefaultPrimary {
	/**
	 * Title field in *VeganMenu → Default → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: This is where it all begins...
	 * - **API ID Path**: vegan_menu.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;
	
	/**
	 * Description field in *VeganMenu → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vegan_menu.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Illustration field in *VeganMenu → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vegan_menu.default.primary.illustration
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	illustration: prismic.ImageField<never>;
}

/**
 * Primary content in *VeganMenu → Items*
 */
export interface VeganMenuSliceDefaultItem {
	/**
	 * BreakfastTitle field in *VeganMenu → Items*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vegan_menu.items[].breakfasttitle
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	breakfasttitle: prismic.TitleField;
	
	/**
	 * Price field in *VeganMenu → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vegan_menu.items[].price
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	price: prismic.NumberField;
	
	/**
	 * Description field in *VeganMenu → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vegan_menu.items[].description
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * DescriptionRichText field in *VeganMenu → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: vegan_menu.items[].descriptionrichtext
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	descriptionrichtext: prismic.RichTextField;
}

/**
 * Default variation for VeganMenu Slice
 *
 * - **API ID**: `default`
 * - **Description**: VeganMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VeganMenuSliceDefault = prismic.SharedSliceVariation<"default", Simplify<VeganMenuSliceDefaultPrimary>, Simplify<VeganMenuSliceDefaultItem>>;

/**
 * Slice variation for *VeganMenu*
 */
type VeganMenuSliceVariation = VeganMenuSliceDefault

/**
 * VeganMenu Shared Slice
 *
 * - **API ID**: `vegan_menu`
 * - **Description**: VeganMenu
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VeganMenuSlice = prismic.SharedSlice<"vegan_menu", VeganMenuSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismicClient.ClientConfig): prismicClient.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismicClient.WriteClientConfig): prismicClient.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismicClient.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			BlogHomeDocument,
			BlogHomeDocumentData,
			BlogHomeDocumentDataSlicesSlice,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			MenuDocument,
			MenuDocumentData,
			MenuDocumentDataMenuLinksItem,
			MenuDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			ReservationsDocument,
			ReservationsDocumentData,
			StandardpageDocument,
			StandardpageDocumentData,
			StandardpageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AddressesBoxSlice,
			AddressesBoxSliceDefaultPrimary,
			AddressesBoxSliceDefaultItem,
			AddressesBoxSliceVariation,
			AddressesBoxSliceDefault,
			AllergyBoxSlice,
			AllergyBoxSliceDefaultPrimary,
			AllergyBoxSliceDefaultItem,
			AllergyBoxSliceVariation,
			AllergyBoxSliceDefault,
			BannerSlice,
			BannerSliceDefaultPrimary,
			BannerSliceVariation,
			BannerSliceDefault,
			BlogPostListSlice,
			BlogPostListSliceDefaultPrimary,
			BlogPostListSliceVariation,
			BlogPostListSliceDefault,
			BookTableSlice,
			BookTableSliceDefaultPrimary,
			BookTableSliceDefaultItem,
			BookTableSliceVariation,
			BookTableSliceDefault,
			DrinksMenuSlice,
			DrinksMenuSliceDefaultPrimary,
			DrinksMenuSliceDefaultItem,
			DrinksMenuSliceVariation,
			DrinksMenuSliceDefault,
			GalleryListSlice,
			GalleryListSliceDefaultItem,
			GalleryListSliceVariation,
			GalleryListSliceDefault,
			HeroSliceSlice,
			HeroSliceSliceDefaultPrimary,
			HeroSliceSliceVariation,
			HeroSliceSliceDefault,
			ImageFeaturedStandardSlice,
			ImageFeaturedStandardSliceDefaultPrimary,
			ImageFeaturedStandardSliceDefaultItem,
			ImageFeaturedStandardSliceVariation,
			ImageFeaturedStandardSliceDefault,
			ImageGallerySlice,
			ImageGallerySliceDefaultPrimary,
			ImageGallerySliceDefaultItem,
			ImageGallerySliceVariation,
			ImageGallerySliceDefault,
			LoveContentSlice,
			LoveContentSliceDefaultPrimary,
			LoveContentSliceVariation,
			LoveContentSliceDefault,
			MainMenuSlice,
			MainMenuSliceDefaultPrimary,
			MainMenuSliceDefaultItem,
			MainMenuSliceVariation,
			MainMenuSliceDefault,
			MapBoxSlice,
			MapBoxSliceDefaultPrimary,
			MapBoxSliceVariation,
			MapBoxSliceDefault,
			StoryFeaturedSlice,
			StoryFeaturedSliceDefaultPrimary,
			StoryFeaturedSliceDefaultItem,
			StoryFeaturedSliceVariation,
			StoryFeaturedSliceDefault,
			TakeAwaySlice,
			TakeAwaySliceDefaultPrimary,
			TakeAwaySliceDefaultItem,
			TakeAwaySliceVariation,
			TakeAwaySliceDefault,
			TeamSliceSlice,
			TeamSliceSliceDefaultPrimary,
			TeamSliceSliceDefaultItem,
			TeamSliceSliceVariation,
			TeamSliceSliceDefault,
			TestimonialsGallerySlice,
			TestimonialsGallerySliceDefaultPrimary,
			TestimonialsGallerySliceVariation,
			TestimonialsGallerySliceDefault,
			TestimonialsMarqueeSlice,
			TestimonialsMarqueeSliceDefaultPrimary,
			TestimonialsMarqueeSliceVariation,
			TestimonialsMarqueeSliceDefault,
			ValuesListSlice,
			ValuesListSliceDefaultPrimary,
			ValuesListSliceVariation,
			ValuesListSliceDefault,
			VeganMenuSlice,
			VeganMenuSliceDefaultPrimary,
			VeganMenuSliceDefaultItem,
			VeganMenuSliceVariation,
			VeganMenuSliceDefault
		}
	}
}